export { knowledgeToolInputSchemas as KNOWLEDGE_TOOL_INPUT_SCHEMAS } from './knowledge-tool-schemas.generated.js'

/** Fields that must never become model-controlled Agent inputs. */
export const FORBIDDEN_AGENT_INPUT_FIELDS = [
  'userId',
  'tenantId',
  'role',
  'roles',
  'permission',
  'permissions',
  'subjectType',
  'datasetId',
  'datasetIds',
  'ragflowDocumentId',
  'versionId',
  'chunkId',
  'sectionId',
  'modelId',
  'llmId',
  'rerankId',
  'pipelineId',
  'similarityThreshold',
  'vectorSimilarityWeight',
  'topK',
  'filters',
  'toc',
  'tocEnhance',
  'kg',
  'deleteAll',
  'cascade',
  'force',
  'includeKnowledgeCompilation',
  'sourcePath',
  'workspaceRoot',
  'body',
  'bytes',
  'base64',
  'partitionId',
  'storageKey',
  'ttl',
  'url',
] as const
